"""добавил парент id

Revision ID: 88828193d4e4
Revises: 19d53715e844
Create Date: 2025-09-30 21:32:59.299780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88828193d4e4'
down_revision: Union[str, Sequence[str], None] = '19d53715e844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('parent_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'parent_id')
    # ### end Alembic commands ###
